name: Update GitHub Stats Gist

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update GitHub Stats Gist
        run: npx github-stats-box@1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 2b3699f10dee3d2c30ef147a4ff2709b
          ALL_COMMITS: true
          K_FORMAT: false
