name: Update GitHub Stats Gist

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github-stats-box
        run: |
          git clone --depth 1 https://github.com/bokub/github-stats-box.git
          cd github-stats-box

          # GitHub API 변경 대응
          perl -0pi -e 's/stargazers \{\s*totalCount\s*\}/stargazerCount/g' fetch.js
          perl -0pi -e 's/curr\.stargazers\.totalCount/curr.stargazerCount/g' index.js

          npm ci

      - name: Update GitHub Stats Gist
        working-directory: github-stats-box
        run: node index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 2b3699f10dee3d2c30ef147a4ff2709b
          ALL_COMMITS: true
          K_FORMAT: false
