name: Update Productive Stats Gist

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Update Productive Stats Gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.PRODUCTIVE_GIST_ID }}
          TIMEZONE: Asia/Seoul
